### PR TITLE
Feature/authentication

### PR DESCRIPTION
**Pull request by rchen45**
Code I read from a flask document online- Still working on changing and adding to it though

### CODE REVIEW

**Comment by nmagerko** [comment]
Instead of putting this functionality in the user module, I think we'll want it in its own module (just an `auth` module will work). That way, if we ever expand to other authentication methods, our endpoints aren't tied to the `user` endpoints.

**Comment by nmagerko** [comment]
As for actually authenticating users, let's use the user service (it's called `UserManager` but I'll rename it later to `UserService` so that it's not as misleading). It should have a method that allows you to check passwords for existing users. Make sure that this is actually an endpoint by the way -- otherwise the app will have plenty of troubles!

**Comment by wchill** [comment]
One more thing, when dealing with passwords/authentication make sure you don't save the real password. Always use what is known as salting + hashing.

How things should work: https://crackstation.net/hashing-security.htm

**Comment by nmagerko** [comment]
Yeah the `UserService`/`UserManager` I wrote uses bcrypt for saving passwords and checking potential passwords, so if we all make sure to use that, I think we'll be alright.

**Comment by rchen45** [comment]
Closing in favor of #6 so that collaborators can work on this feature as well.

**Pull request closed without merging**
